function figureall(texdir, figuredir, texname)
% FIGUREALL(texdir, figuredir, foutname)
%
% Generates a tex file containing all figures in the directory with some
% generic caption.
%
% INPUT:
% texdir        fullpath directory of the tex file and figuredir
% figuredir     directory of the figures inside texdir [default: 'figures/']
% texname       filename of the tex file [default: 'main.tex']
%
% Last modified by sirawich-at-princeton.edu, 01/14/2023

defval('figuredir', 'figures')
defval('texname', 'main.tex')

% fullpath to the figure folder
figuredir_full = fullfile(texdir, figuredir);

% gather all figure files
% TODO: filter out the files that are not figures
allfigurefiles = ls2cell(figuredir_full, 0);

% create the tex file
texfile = fullfile(texdir, texname);
system(sprintf('touch %s', texfile));

%% write the tex file
fid = fopen(texfile, 'w');

% include packages
fprintf(fid, '\\documentclass[12pt,letterpaper]{article}\n');
fprintf(fid, '\\usepackage[utf8]{inputenc}\n');
fprintf(fid, '\\usepackage{amsmath}\n');
fprintf(fid, '\\usepackage{graphicx}\n');
fprintf(fid, '\\usepackage{subcaption}\n');
fprintf(fid, '\\usepackage{float}\n');
fprintf(fid, '\\usepackage{geometry}\n');
fprintf(fid, '\\usepackage{bm}\n');
fprintf(fid, '\\usepackage{hyperref}\n');
fprintf(fid, '\\usepackage{natbib}\n');
fprintf(fid, '\\usepackage{grffile}\n');
fprintf(fid, '\n');

% paper geometry
fprintf(fid, '\\geometry{\n');
fprintf(fid, '    letterpaper,\n');
fprintf(fid, '    left=25mm,\n');
fprintf(fid, '    top=25mm,\n');
fprintf(fid, '    bottom=25mm,\n');
fprintf(fid, '    right=25mm\n');
fprintf(fid, '}\n');
fprintf(fid, '\n');

% document header
% TODO: make them accept input parameters (maybe as a struct)
fprintf(fid, '\\title{Autogenerated from figureall.m}\n');
fprintf(fid, '\\author{Sirawich Pipatprathanporn}\n');
fprintf(fid, '\\date{\\today}\n');
fprintf(fid, '\n');

% document section
fprintf(fid, '\\begin{document}\n');
fprintf(fid, '\n');
fprintf(fid, '\\maketitle\n');
fprintf(fid, '\n');

% loop through all figures
for ii = 1:length(allfigurefiles)
    fprintf(fid, '\\begin{figure}[hbt]\n');
    fprintf(fid, '    \\centering\n');
    command_string1 = '\\includegraphics';
    command_string2 = '\\linewidth';
    fprintf(fid, ...
        sprintf('    %s[width=0.8%s]{%s%s}\n', ...
        command_string1, command_string2, figuredir, allfigurefiles{ii}));
    % get the name of the file without the extension
    [~, name, ~] = fileparts(allfigurefiles{ii});
    command_string3 = '\\caption';
    command_string4 = '\\label';
    fprintf(fid, ...
        sprintf('    %s{%s{fig:%s} Bla bla.}\n', command_string3, ...
        command_string4, name));
    fprintf(fid, '\\end{figure}\n');
    fprintf(fid, '\n');
    if ii < length(allfigurefiles)
        fprintf(fid, '\\clearpage\n');
        fprintf(fid, '\n');
    end
end

fprintf(fid, '\\end{document}\n');

% close the file
fclose(fid);
end