function [tims, seisdata] = getarrivaltemplate(ddir, station, r)
% [tims, seisdata] = GETARRIVALTEMPLATE(ddir, station, r)
%
% Returns the waveform of the first phase arrival assuming the most direct
% path from the source array to the receiver. This function only works with
% simulation outputs of generated by specfem2d where the input files are
% generated by SPECFEM2D_INPUT_SETUP_FLAT. It assumes line of sources to
% create plane waves at any incident angle and a single receiver within the
% same medium as the sources.
%
% INPUT:
% ddir          simulation directory
% station       either 'bottom' [default] or 'hydrophone'
% r             the fraction of the window that is tapered [default: 0.1]
%
% OUTPUT:
% tims          times of the signal
% seisdata      signal
%
% SEE ALSO:
% READ_SEISMOGRAM, SPECFEM2D_INPUT_SETUP_FLAT
%
% Last modified by sirawich-at-princeton.edu, 02/16/2024

defval('station', 'bottom')
defval('r', 0.1)

% the end of the earthquake relative to the centroid time
t_end = 1;

% read source file
sources = loadsource(sprintf('%sDATA/SOURCE', ddir));
x0 = sources{1}.xs;
z0 = sources{1}.zs;
t0 = sources{1}.tshift;
dt = sources{2}.tshift - sources{1}.tshift;
dx = sources{2}.xs - sources{1}.xs;

% read the station file
[~, name, network, x, z] = read_stations(sprintf('%sDATA/STATIONS', ddir));

% read parameter file
params = loadparfile(sprintf('%sDATA/Par_file', ddir));
vp = params.MODELS{1}.vp;       % P-wave velocity in the solid
vc = params.MODELS{2}.vp;       % P-wave (acoustic) velocity in the fluid

% calculate when the wave front arrive if it originates at t=0
theta = asin(dt * vp / dx);
if strcmpi(station, 'bottom')
    t_travel = ((x(2) - x0) * sin(theta) + (z(2) - z0) * cos(theta)) / vp;
    % read the seismogram
    % try to read the binary file output first then try to read ASCII
    try
        par_file = sprintf('%sDATA/Par_file', ddir);
        tims = specfem2dtime(par_file, 2, sprintf('%sDATA/SOURCE', ddir));
        try
            data = freadseismograms(sprintf(...
                '%s/OUTPUT_FILES/Uz_file_single_d.bin', ddir), par_file);
        catch ME
            try
                data = freadseismograms(sprintf(...
                    '%s/OUTPUT_FILES/Uz_file_double_d.bin', ddir), par_file);
            catch
            end
        end
        seisdata = data(:,2);
    catch ME
        try
            [tims, seisdata] = read_seismogram(sprintf('%sOUTPUT_FILES/%s.%s.BXZ.semd', ...
                ddir, network{2}, name{2}));
        catch ME
            [tims, seisdata] = read_seismogram(sprintf('%sOUTPUT_FILES/%s.%s.PRE.semp', ...
                ddir, network{2}, name{2}));
        end
    end
else
    theta_w = asin(vc / vp * sin(theta));
    t_travel_solid = ((x(2) - (z(1) - z(2)) * tan(theta_w) - x0) * ...
        sin(theta) + (z(2) - z0) * cos(theta)) / vp;
    t_travel_fluid = (z(1) - z(2)) / cos(theta_w) / vc;
    t_travel = t_travel_solid + t_travel_fluid;
    % read the seismogram
    try
        [tims, seisdata] = read_seismogram(sprintf('%sOUTPUT_FILES/%s.%s.BXZ.semd', ...
            ddir, network{1}, name{1}));
    catch
        [tims, seisdata] = read_seismogram(sprintf('%sOUTPUT_FILES/%s.%s.PRE.semp', ...
            ddir, network{1}, name{1}));
    end
end

% remove any signal after the end of the first arrival
wh = (tims > t0 + t_end + t_travel);
seisdata(wh) = 0;

% smooth the end of the first arrival
seisdata(~wh) = seisdata(~wh) .* shanning(length(seisdata(~wh)), r);
end