function [tims, seisdata] = getarrivaltemplate(ddir, example)
% [tims, seisdata] = GETARRIVALTEMPLATE(ddir, example)
%
% Returns the waveform of the first phase arrival assuming the most direct
% path from the source array to the receiver. This function only works with
% simulation outputs of generated by specfem2d where the input files are
% generated by SPECFEM2D_INPUT_SETUP_FLAT. It assumes line of sources to
% create plane waves at any incident angle and a single receiver within the
% same medium as the sources.
%
% INPUT:
% ddir          simulation directory
% example       name for the model
%
% OUTPUT:
% tims          times of the signal
% seisdata      signal
%
% SEE ALSO:
% READ_SEISMOGRAM, SPECFEM2D_INPUT_SETUP_FLAT
%
% Last modified by sirawich-at-princeton.edu, 11/05/2021

% read source-time function file
fid = fopen(sprintf('%sOUTPUT_FILES/plot_source_time_function.txt', ddir), 'r');
data = fscanf(fid, '%f %f\n', [2 Inf]);
fclose(fid);
t = data(1,:)';
s = data(2,:)';

% identify the end of the earthquake
%wh = (abs(s) > 0);
t_end = 1; %max(t(wh));

% read source file
sources = loadsource(sprintf('%sDATA/SOURCE_%s', ddir, example));
x0 = sources{1}.xs;
z0 = sources{1}.zs;
t0 = sources{1}.tshift;
dt = sources{2}.tshift - sources{1}.tshift;
dx = sources{2}.xs - sources{1}.xs;

% read the station file
[~, name, network, x, z] = read_stations(sprintf('%sDATA/STATIONS', ddir));

% read parameter file
params = loadparfile(sprintf('%sDATA/Par_file_%s', ddir, example));
vp = params.MODELS{1}.vp;

% calculate when the wave front arrive if it originates at t=0
theta = asin(dt * vp / dx);
t_travel = ((x(2) - x0) * sin(theta) + (z(2) - z0) * cos(theta)) / vp;

% read the seismogram
[tims, seisdata] = read_seismogram(sprintf('%sOUTPUT_FILES/%s.%s.BXZ.semd', ...
    ddir, network{2}, name{2}));

% remove any signal after the end of the first arrival
wh = (tims > t0 + t_end + t_travel);
seisdata(wh) = 0;
end